spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Librarycrud
    username: postgres
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: huy.tranvan.ncc@gmail.com
    password: fsbetbqgpbhdpadw
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp

minio:
  url: http://localhost:9000
  access:
    key: minioadmin
    secret: minioadmin
  bucket:
    name: librarycrud